---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
    yamllint .
    ansible-lint
    flake8
platforms:
  - name: postgresql14
    image: ubuntu:22.04
  - name: postgresql15
    image: ubuntu:22.04
  - name: postgresql16
    image: ubuntu:22.04
  - name: postgresql17
    image: ubuntu:22.04
  - name: postgresql18
    image: ubuntu:22.04
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      postgresql14:
        postgresql_version: "14"
      postgresql15:
        postgresql_version: "15"
      postgresql16:
        postgresql_version: "16"
      postgresql17:
        postgresql_version: "17"
      postgresql18:
        postgresql_version: "18"
  playbooks:
    converge: ../resources/playbook.yml
scenario:
  name: ubuntu2204
verifier:
  name: testinfra
  directory: ../resources/tests/
